# Build Environment
build_environment: Ubuntu 12.04
 
 # language setting
language: php
  # php tag
php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 
# only build when certain Git branches are updated
branches:
  only:
    - gh-pages
    - master

before_script:
  - mkdir -p shippable/codecoverage

script: php -l
 
# Notification
notifications:
  email:
    recipients:
      - djdefi@gmail.com
    on_success: always
    on_failure: change
