# Site settings
title: DJ DeFi 
description: > # this means to ignore newlines until "baseurl:"
  DJ DeFi west coast Drum and Bass DJ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://djdefi.com" # the base hostname & protocol for your site
twitter_username: djdefi

# Build settings
markdown: kramdown
