name: CI
on:
  push:
    branches: [ master, gh-pages ]
  pull_request:
    branches: [ master, gh-pages ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - name: cibuild
      run: ./script/cibuild

    - name: Jekyll Screenshot
      uses: hakierspejs/jekyll-screenshot-github-action@1.0
    - uses: actions/upload-artifact@v1
      with:
       name: screenshot
       path: /home/runner/work/_temp/_github_home/screenshot.png
